vich_uploader:
    db_driver: orm

    mappings:
        franchise_images :
            uri_prefix: /images/products
            upload_destination: '%kernel.project_dir%/public/images/franchise'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
